#server:
#    port: 8080
##spring
#spring:
#  devtools:
#    restart:
#      enabled: true     #这里是为了热部署的，与mybatis是无关的
#  #DATABASE CONFIG
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: root
#    url: jdbc:mysql://mysqldb:3306/tdx_shop?useUnicode=true&characterEncoding=utf-8
#    type: com.alibaba.druid.pool.DruidDataSource   #这里是配置druid连接池，以下都是druid的配置信息
#    filters: stat,wall,log4j
#    maxActive: 20
#    initialSize: 1
#    maxWait: 60000
#    minIdle: 1
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: select 'x'
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxOpenPreparedStatements: 20
#    connection-properties: druid.stat.merggSql=ture;druid.stat.slowSqlMillis=5000
#
##mybatis
#mybatis:
#  mapper-locations: classpath*:/mapper/**Mapper.xml   #把xml文件放在com.XX.mapper.*中可能会出现找到的问题，这里把他放在resource下的mapper中
#  #实体扫描，多个package用逗号或者分号分隔
#  typeAliasesPackage: com.tdx.account_service.entity  #这里是实体类的位置
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: false
##logging
#logging:
#  level: warn